[0m01:04:06.041309 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a77152a98d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a7714253a60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a7714253a00>]}


============================== 01:04:06.044067 | 9cc53ce6-4415-409a-a736-32d8fd4ba19f ==============================
[0m01:04:06.044067 [info ] [MainThread]: Running with dbt=1.10.13
[0m01:04:06.044406 [debug] [MainThread]: running dbt with arguments {'static_parser': 'True', 'debug': 'False', 'cache_selected_only': 'False', 'invocation_command': 'dbt docs generate', 'profiles_dir': '/home/raymon/.dbt', 'indirect_selection': 'eager', 'introspect': 'True', 'write_json': 'True', 'printer_width': '80', 'log_path': '/home/raymon/DE-projects/dbt-cars-comparsion/logs', 'empty': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'log_format': 'default', 'warn_error': 'None', 'quiet': 'False', 'log_cache_events': 'False', 'fail_fast': 'False', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'partial_parse': 'True', 'version_check': 'True', 'send_anonymous_usage_stats': 'True', 'no_print': 'None'}
[0m01:04:06.047502 [info ] [MainThread]: Error importing adapter: No module named 'dbt.adapters.postgres'
[0m01:04:06.047824 [error] [MainThread]: Encountered an error:
Runtime Error
  Credentials in profile "cars_details", target "dev" invalid: Runtime Error
    Could not find adapter type postgres!
[0m01:04:06.050355 [debug] [MainThread]: Resource report: {"command_name": "generate", "command_success": false, "command_wall_clock_time": 0.05455552, "process_in_blocks": "14384", "process_kernel_time": 0.116709, "process_mem_max_rss": "94860", "process_out_blocks": "8", "process_user_time": 0.914225}
[0m01:04:06.051031 [debug] [MainThread]: Command `dbt docs generate` failed at 01:04:06.050947 after 0.06 seconds
[0m01:04:06.051322 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a77152a98d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a7714253520>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a7714251990>]}
[0m01:04:06.051576 [debug] [MainThread]: Flushing usage events
[0m01:04:06.896928 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m01:05:36.999862 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x769a5c879840>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x769a5b7ffa00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x769a5b7ff9a0>]}


============================== 01:05:37.002532 | 18e3e086-68c8-40fd-ae26-58bc60fd93dd ==============================
[0m01:05:37.002532 [info ] [MainThread]: Running with dbt=1.10.13
[0m01:05:37.003083 [debug] [MainThread]: running dbt with arguments {'empty': 'None', 'use_experimental_parser': 'False', 'partial_parse': 'True', 'use_colors': 'True', 'write_json': 'True', 'introspect': 'True', 'quiet': 'False', 'version_check': 'True', 'static_parser': 'True', 'log_path': '/home/raymon/DE-projects/dbt-cars-comparsion/logs', 'send_anonymous_usage_stats': 'True', 'cache_selected_only': 'False', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'target_path': 'None', 'log_cache_events': 'False', 'profiles_dir': '/home/raymon/.dbt', 'invocation_command': 'dbt docs generate', 'indirect_selection': 'eager', 'fail_fast': 'False', 'log_format': 'default', 'no_print': 'None', 'debug': 'False', 'printer_width': '80', 'warn_error': 'None'}
[0m01:05:37.007021 [info ] [MainThread]: Error importing adapter: No module named 'dbt.adapters.postgres'
[0m01:05:37.007416 [error] [MainThread]: Encountered an error:
Runtime Error
  Credentials in profile "cars_details", target "dev" invalid: Runtime Error
    Could not find adapter type postgres!
[0m01:05:37.009413 [debug] [MainThread]: Resource report: {"command_name": "generate", "command_success": false, "command_wall_clock_time": 0.062263478, "process_in_blocks": "25800", "process_kernel_time": 0.116365, "process_mem_max_rss": "94480", "process_out_blocks": "16", "process_user_time": 0.926908}
[0m01:05:37.009864 [debug] [MainThread]: Command `dbt docs generate` failed at 01:05:37.009790 after 0.06 seconds
[0m01:05:37.010086 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x769a5c879840>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x769a5b7ff460>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x769a5b7fd990>]}
[0m01:05:37.010311 [debug] [MainThread]: Flushing usage events
[0m01:05:37.839178 [debug] [MainThread]: An error was encountered while trying to flush usage events
